output_subdir: null

model:
    S: 7
    B: 2 # Number of bouding box per grid cell
    C: 20 # Number of class for classify task 
    in_channels: 3
    fc_hidden_feature: 4096    
    wandb: True

    train: 
        device: cuda
        epochs: 135
        lr: 10e-4
        momentum: 0.9
        weight_decay: 5.0e-4

        loss:
            coord_lambda: 5.0
            noobj_lambda: 0.5

        dataset:
            batch_size: 64
            pin_memory: false
            shuffle: true
            drop_last: true
            train_data:
                _target_: dataset.VOCDataset
                csv_file: data/train.csv
                label_dir: data/labels
                image_dir: data/images
            test_data:
                _target_: dataset.VOCDataset
                csv_file: data/test.csv
                label_dir: data/labels
                image_dir: data/images
    
    evaluate:
        device: cuda

        pretrained_path: log/01-04-2024/11-02

        dataset:
            batch_size: 64
            pin_memory: false
            shuffle: true
            drop_last: true
            test_data:
                _target_: dataset.VOCDataset
                csv_file: data/test.csv
                label_dir: data/labels
                image_dir: data/images

    log:
        _target_: utils.save_model
        save_weight_only: true
        overwrite_dir: true
  